# Generated by Django 5.2.5 on 2025-09-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
    ]
