# Generated by Django 5.2.5 on 2025-09-20 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('country', models.CharField(default='PS', max_length=3)),
                ('phone', models.CharField(default='', max_length=20)),
                ('phone_is_verified', models.BooleanField(default=False)),
                ('reset_code', models.CharField(blank=True, max_length=4, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('available_to_create_car', models.BooleanField(default=False)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authentication.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
