# Generated by Django 5.2.6 on 2025-10-01 20:30

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_country_remove_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.user_profile_image_path),
        ),
    ]
