# Generated by Django 5.2.6 on 2025-10-02 15:08

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default/profile/profile.jpg', null=True, upload_to=authentication.models.user_profile_image_path),
        ),
    ]
