# Generated by Django 5.2.6 on 2025-10-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id']},
        ),
    ]
