# Generated by Django 5.2.5 on 2025-09-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_verified',
            new_name='phone_is_verified',
        ),
    ]
