# Generated by Django 5.2.5 on 2025-09-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_rename_phone_verified_user_phone_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
