# Generated by Django 5.2.5 on 2025-09-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
