# Generated by Django 5.2.5 on 2025-09-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price_per_day',
        ),
        migrations.AddField(
            model_name='car',
            name='daily_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_for_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='is_for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='monthly_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='weekly_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='yearly_rent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
