# Generated by Django 5.2.6 on 2025-09-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_price_per_day_car_daily_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seating_capacity',
            field=models.PositiveSmallIntegerField(blank=True, default='4', null=True),
        ),
    ]
