# Generated by Django 5.2.6 on 2025-09-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_seating_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('luxury', 'Luxury')], default='regular', max_length=10),
        ),
    ]
