# Generated by Django 5.2.6 on 2025-10-09 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_review_user_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='carfeature',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
