# Generated by Django 5.2.5 on 2026-02-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_brand_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
